import type { LucideIcon } from 'lucide-react'
import {
  Archive,
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Ban,
  Blocks,
  Building,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronRight,
  CircleDot,
  CircleUser,
  Clock4,
  Columns3,
  Crown,
  Database,
  DoorOpen,
  Eye,
  FileText,
  FolderOpen,
  Gauge,
  Globe,
  Grid2x2,
  Grid3x3,
  HandCoins,
  HardHat,
  KeyRound,
  Landmark,
  LayoutGrid,
  ListTodo,
  Lock,
  Mail,
  MapPin,
  Menu,
  Network,
  Phone,
  Plane,
  Quote,
  Receipt,
  Rocket,
  Rows3,
  Scale,
  ScanLine,
  ScrollText,
  Send,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Timer,
  UserCog,
  Users,
  UsersRound,
  Wallet,
  Workflow,
  X,
  Zap,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  archive: Archive,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'badge-check': BadgeCheck,
  ban: Ban,
  blocks: Blocks,
  building: Building,
  'calendar-clock': CalendarClock,
  'calendar-days': CalendarDays,
  'chart-column': ChartColumn,
  check: Check,
  'check-check': CheckCheck,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  'circle-user': CircleUser,
  clock4: Clock4,
  'columns-3': Columns3,
  crown: Crown,
  database: Database,
  'door-open': DoorOpen,
  eye: Eye,
  'file-text': FileText,
  'folder-open': FolderOpen,
  gauge: Gauge,
  globe: Globe,
  'grid-2x2': Grid2x2,
  'grid-3x3': Grid3x3,
  'hand-coins': HandCoins,
  'hard-hat': HardHat,
  'key-round': KeyRound,
  landmark: Landmark,
  'layout-grid': LayoutGrid,
  'list-todo': ListTodo,
  lock: Lock,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  network: Network,
  phone: Phone,
  plane: Plane,
  quote: Quote,
  receipt: Receipt,
  rocket: Rocket,
  'rows-3': Rows3,
  scale: Scale,
  'scan-line': ScanLine,
  'scroll-text': ScrollText,
  send: Send,
  'settings-2': Settings2,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  timer: Timer,
  'user-cog': UserCog,
  users: Users,
  'users-round': UsersRound,
  wallet: Wallet,
  workflow: Workflow,
  x: X,
  zap: Zap,
}